# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geowarin blog
author: Geoffroy Warin
email: geowarin@gmail.com
description: >
  Web developer
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geowarin.github.io" # the base hostname & protocol for your site
paginate: 10 # The number of posts to show per page on your homepage

name: 'Geoffroy Warin'
bio: >
  Hello! I write codez

author_image: "/assets/images/author.jpg"
twitter:
  username: geowarin
github:
  username: geowarin

google_site_verification: To-lHBJ-1nWMoTSlWKsL3keqsH2cKS2xYp8gJ3Omq9g

google-analytics:
  tracking_id : 'UA-46024908-1'

disqus:
  shortname: geowarin

# https://pages.github.com/versions/
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jemoji

permalink: :title.html

exclude:
    - .sass-cache
    - .idea